// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_leaderboard = new UnifiedLeaderboard("Leaderboard",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIir-T-ugeEAIQAA"
#else
            "Leaderboard"
#endif
            );

        public static UnifiedLeaderboard Leaderboard
        {
            get { return s_leaderboard; }
        }

        private static readonly UnifiedLeaderboard s_anotherLeaderboard = new UnifiedLeaderboard("AnotherLeaderboard",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIir-T-ugeEAIQAg"
#else
            "AnotherLeaderboard"
#endif
            );

        public static UnifiedLeaderboard AnotherLeaderboard
        {
            get { return s_anotherLeaderboard; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "Leaderboard", s_leaderboard },
            { "AnotherLeaderboard", s_anotherLeaderboard },
        };
    }
}
